title: 'Per "Pierre" Jørgensen'
url: "https://pierrejorgensen.github.io"
baseurl: ""

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - .node-version
  - README.md
  - Script
  - scripts
  - .github
  - .staticrypt.json
  - .env
  - .env.example
  - ssh_key
  - ssh_key.pub
  - .DS_Store
  - Assets/.DS_Store
  - Assets/index/.DS_Store
  - Assets/work-fitness-tracking-application/.DS_Store
